### ISSUE TITLE
Change Home page bullet point

### ISSUE THREAD

**Issue by Jessekrich** [brainglobe/brainglobe.github.io#10]
**Describe the bug**

**To Reproduce**
Please enter full details of how to reproduce this bug.

**Expected behaviour**

**Log file**
Please attach the log file if relevant (e.g. `output/cellfinder_2019-12-17_13-29-46.log`)

**Screenshots**

**Computer used (please complete the following information):**

- OS: [e.g. Linux, Windows, macOS] For macOS, please specify if you have an Intel or M1 CPU (M1 is likely if your mac is new).
- Version [e.g. 18.04]
- Hardware specs [e.g. 128 GB RAM, Xeon 4114 CPU].

**Additional context**

**Comment by Jessekrich** [comment]
On the BrainGlobe home page it says 3 main points, and contains 3 sentences yet 4 bullet points.

**Comment by adamltyson** [comment]
Fixed in e9150eafbd7496828dfcb17a192e25b10d793846. Thanks @Jessekrich!
