### ISSUE TITLE
Update docs to suggest Python 3.11

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe.github.io#108]
[This page](https://brainglobe.info/documentation/setting-up/conda.html#setup-your-conda-environment) suggests installing Python 3.10. Can we move to Python 3.11 or do we have outstanding issues (e.g. TensorFlow).

cc @brainglobe/active-devs

**Comment by willGraham01** [comment]
I know that at least `cellfinder` (and core, napari), and `workflows` do not have python 3.11 in their test suite (although whether they fail when run on python 3.11 is another question).

The tensorflow issue is tied to our failing tests in the more recent versions: https://github.com/brainglobe/cellfinder-core/issues/103. Not sure if this means python 3.11 is incompatible. There's also the separate `conda install` issue with TensorFlow that may cause problems.

**Comment by adamltyson** [comment]
> I know that at least cellfinder (and core, napari), and workflows do not have python 3.11 in their test suite (although whether they fail when run on python 3.11 is another question).

[One way to find out](https://github.com/brainglobe/cellfinder-core/pull/228)

**Comment by willGraham01** [comment]
From the link, looks like the answer is no. More reason to prioritise moving away from TensorFlow?
