### ISSUE TITLE
Update colors to make hyperlinks more obvious

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe.github.io#13]

**Comment by adamltyson** [comment]
@niksirbi would you be able to take a look at this? I defer to your superior intuition when it comes to color palettes!

**Comment by niksirbi** [comment]
Certainly. Can this wait till next week or do you need it today?

**Comment by adamltyson** [comment]
No rush. The site is working fine, it's just the links aren't very clear in light mode. Thanks!

**Comment by adamltyson** [comment]
They're also pretty hard to see in dark mode

**Comment by adamltyson** [comment]
Not sure why this wasn't closed automatically with #22, but the links look good now. Thanks again @niksirbi!
