### ISSUE TITLE
[Feature] document cave fish atlas

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainglobe.github.io#192]
**Is your feature request related to a problem? Please describe.**
We're about to add a cavefish atlas to the Atlas API. 

**Describe the solution you'd like**
We should at least mention this in the list of available atlases (and also maybe write a blog post/announce in some other way?)

**Describe alternatives you've considered**

\

**Additional context**

https://github.com/brainglobe/brainglobe-atlasapi/pull/277

**Comment by adamltyson** [comment]
I think a short blogpost would be nice. It could include some screenshots, and it also makes advertising elsewhere easier (we can just link to the blog).

**Comment by adamltyson** [comment]
Reopening this because the atlas isn't listed [here](https://brainglobe.info/documentation/brainglobe-atlasapi/index.html).
