### ISSUE TITLE
Document how to analyse layers from other plugins using brainreg-segment

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe.github.io#29]
This is the feature added in https://github.com/brainglobe/brainreg-segment/issues/73

cc @SaraMederos

**Comment by SaraMederos** [comment]
Documentation for the feature added in brainglobe/brainreg-segment#73 will be ready for 23/06/23

**Comment by adamltyson** [comment]
I should also add the relevant docs for doing the same with 1D tracks.

**Comment by SaraMederos** [comment]
Documentation for #73 is now included as a PR, working on a tutorial for generating visualizations from the external layers and specific example
