### ISSUE TITLE
Add a simple tutorial outlining brainreg-segment

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe.github.io#83]
Just show how to segment a simple track and region. Can we provide a brainreg output directory as sample data? Or maybe follow on from the registration tutorial (#82)?

**Comment by alessandrofelder** [comment]
Presumably this can consist of moving and adapting https://brainglobe.info/documentation/brainglobe-segmentation/user-guide/segmenting-1d-tracks.html @adamltyson ?

**Comment by adamltyson** [comment]
Yep, and also https://brainglobe.info/documentation/brainglobe-segmentation/user-guide/segmenting-3d-structures.html
