### ISSUE TITLE
Check all links with linkcheck

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe.github.io#97]
See https://github.com/neuroinformatics-unit/actions/pull/24 for details

**Comment by adamltyson** [comment]
I started this at #100. Checking all the links takes a long time on this repo due to the sheer number. I think it's probably worth making sure the links are correct at the expense of slowing down deployment. What do you think @alessandrofelder?

**Comment by alessandrofelder** [comment]
> I think it's probably worth making sure the links are correct at the expense of slowing down deployment.
Definitely, and I would implement this if we know how to do it before optimising further.
After that, we can think about whether it's possible to run this or another tool only on the diff?
